#!/bin/bash

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C)  TinyTools

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, version 3 of the License.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

cat << EOF > pyprochtml
#!/usr/bin/python
import sys 
file_content=str()
for line in sys.stdin: 
    file_content+=line
content_splited = file_content.split('<hr />')
for slide in content_splited:
    print('<section>')
    print(slide.strip())
    print('</section>')
EOF

tmp_folder=/tmp/tmdpress

usage()
{
    echo "tmdpress presentation.md"
    exit 1
}

create_tmp_folder()
{
    mkdir -p "$tmp_folder"
}

copy_template_files()
{
    filename="$1"
    header_pres="header_${filename%.*}.html"
    footer_pres="footer_${filename%.*}.html"
    cp _header.html "$tmp_folder/$header_pres"
    cp _footer.html "$tmp_folder/$footer_pres"
}

fill_metadata()
{
    filename="$1"
    header_pres="header_${filename%.*}.html"
    title=$(tyaml $filename -v title)
    header=$(tyaml $filename -v header)
    footer=$(tyaml $filename -v footer)
    content=$(cat $filename)
    sed -i "s+__TITLE__+$title+g" "$tmp_folder/$header_pres"
    sed -i "s+__HEADER__+$header+g" "$tmp_folder/$header_pres"
    sed -i "s+__FOOTER__+$footer+g" "$tmp_folder/$header_pres"
}

convert_md_to_html()
{
    filename="$1"
    pandoc_filename="pandoc_${filename%.*}".html
    pandoc "$filename" -t html | process_html_file > "$tmp_folder/$pandoc_filename"
}

process_html_file()
{
    python pyprochtml
}

create_presentation()
{
    filename="$1"
    pres_filename="${filename%.*}".html
    pandoc_filename="pandoc_${filename%.*}".html
    header_pres="header_${filename%.*}.html"
    footer_pres="footer_${filename%.*}.html"
    cat $tmp_folder/$header_pres $tmp_folder/$pandoc_filename $tmp_folder/$footer_pres > $pres_filename
}

remove_tmp_folder()
{
    rm -fr "$tmp_folder"
}

[ -z "$1" ] && usage

filename=$1

[ -d $tmp_folder ] &&  rm -fr remove_tmp_folder

create_tmp_folder

copy_template_files "$filename"
fill_metadata "$filename"
convert_md_to_html "$filename"
create_presentation "$filename"

echo "OK!"
